name: 'Release: Maven Central'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish to Maven Central
        env:
          CENTRAL_PUBLISHER_USERNAME: ${{ secrets.CENTRAL_PUBLISHER_USERNAME }}
          CENTRAL_PUBLISHER_PASSWORD: ${{ secrets.CENTRAL_PUBLISHER_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew clean publishJsPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository --stacktrace
